name: 🏛️ Propuesta Legislativa Interna
description: Para miembros del Alto Congreso Tlatocan
title: '[LEGISLATIVO] '
labels: ['legislativo', 'reforma-constitucional']
assignees:
  - Secretario-Congreso
body:
  - type: markdown
    attributes:
      value: |
        ## 🏛️ PROPUESTA LEGISLATIVA INTERNA
        
        **Autorización:** ✅ MIEMBRO DEL ALTO CONGRESO TLATOCAN  
        **Proceso:** 🚀 ACELERADO (3 días mínimo de debate)
        
  - type: input
    id: proponente
    attributes:
      label: 📋 Legislador Proponente
      description: Tu usuario de GitHub
      placeholder: "@tu-usuario"
    validations:
      required: true
      
  - type: input
    id: especialidad
    attributes:
      label: 🎯 Área de Especialidad
      description: Tu área de expertise legislativa
      placeholder: "Ej: Derecho Constitucional, Reforma Judicial, etc."
    validations:
      required: true
      
  - type: dropdown
    id: tipo-cambio
    attributes:
      label: 📊 Tipo de Cambio (Versionado Semántico)
      description: Impacto esperado de la reforma
      options:
        - MAJOR - Cambio estructural profundo
        - MINOR - Nueva funcionalidad o artículo  
        - PATCH - Corrección menor o clarificación
    validations:
      required: true
      
  - type: textarea
    id: articulos-afectados
    attributes:
      label: 📜 Artículos Afectados
      description: Lista específica de artículos que se modificarán
      placeholder: "Ej: Artículo 15, Artículo 23, Título III"
    validations:
      required: true
      
  - type: textarea
    id: situacion-actual
    attributes:
      label: 📖 Situación Actual
      description: Texto constitucional actual que se desea modificar
      placeholder: "Copia exacta del artículo o disposición actual..."
    validations:
      required: true
      
  - type: textarea
    id: propuesta-reforma
    attributes:
      label: ✏️ Propuesta de Reforma
      description: Nueva redacción propuesta
      placeholder: "Texto exacto de la nueva redacción..."
    validations:
      required: true
      
  - type: textarea
    id: justificacion
    attributes:
      label: 💡 Justificación Legislativa
      description: Análisis jurídico y fundamento constitucional
      placeholder: |
        **Problema identificado:**
        - Descripción del problema actual
        
        **Fundamento constitucional:**
        - Artículos que respaldan el cambio
        
        **Precedentes:**
        - Casos similares o antecedentes
    validations:
      required: true
      
  - type: textarea
    id: impacto
    attributes:
      label: 📊 Análisis de Impacto
      description: Evaluación de consecuencias y beneficios
      placeholder: |
        **Afectados directos:**
        - Quiénes se ven impactados
        
        **Cambios operacionales:**
        - Qué procesos cambiarían
        
        **Recursos necesarios:**
        - Recursos técnicos, humanos, etc.
    validations:
      required: true
      
  - type: input
    id: cronograma
    attributes:
      label: 🗓️ Cronograma Propuesto
      description: Fecha estimada para votación e implementación
      placeholder: "Ej: Votación en 1 semana, implementación inmediata"
    validations:
      required: false
      
  - type: checkboxes
    id: pre-validacion
    attributes:
      label: ✅ Pre-validación Legislativa
      description: Confirma que has completado estos pasos
      options:
        - label: Revisión de constitucionalidad completada
          required: true
        - label: Consulta con especialistas realizada  
          required: false
        - label: Análisis de precedentes efectuado
          required: false
        - label: Evaluación de recursos necesarios
          required: true
        - label: Preparación de documentación técnica
          required: true
          
  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🚀 Proceso Acelerado Habilitado
        
        Como miembro del Alto Congreso Tlatocan, esta propuesta seguirá el **proceso acelerado**:
        - ⏱️ **Mínimo 3 días** de debate público
        - 🗳️ **Votación directa** sin pre-aprobación
        - ⚡ **Implementación rápida** tras aprobación
        
        **Base legal:** Artículos 15, 16 y 35 de la Constitución v3.0.0